In [1]:
import numpy as ny
import pandas as pd

In [2]:
data = pd.read_csv("10_percent_weather.csv")
data["consumption_city_kWh"] = data["Trip Miles"].apply(lambda x:(x*28.09/100))
data["consumption_combined_kWh"] = data["Trip Miles"].apply(lambda x:(x*30.13/100))
data.head()

,Unnamed: 0,Trip ID,Trip Start Timestamp,Trip End Timestamp,Trip Seconds,Trip Miles,Trips Pooled,Pickup Centroid Latitude,Pickup Centroid Longitude,Dropoff Centroid Latitude,Dropoff Centroid Longitude,max_temp,min_temp,precip,Trip min,consumption_city_kWh,consumption_combined_kWh
0,0,01fb7b0a39770bf4030110323f25e564bd46deb0,2019-01-01 00:00:00,01/01/2019 12:00:00 AM,249.0,0.8,1,41.970245,-87.713435,41.964652,-87.721017,2.8,2.2,1.0,4,0.22472,0.24104
1,1,01fb7b0a39770bf4030110323f25e564bd46deb0,2019-01-01 00:00:00,01/01/2019 12:00:00 AM,249.0,0.8,1,41.970245,-87.713435,41.964652,-87.721017,2.8,2.8,1.0,4,0.22472,0.24104
2,2,02de4893ce2de28b50976cc723f98cc8d325f9d5,2019-01-01 00:00:00,01/01/2019 12:15:00 AM,445.0,1.7,1,41.859350,-87.617358,41.863423,-87.653757,2.8,2.2,1.0,7,0.47753,0.51221
3,3,02de4893ce2de28b50976cc723f98cc8d325f9d5,2019-01-01 00:00:00,01/01/2019 12:15:00 AM,445.0,1.7,1,41.859350,-87.617358,41.863423,-87.653757,2.8,2.8,1.0,7,0.47753,0.51221
4,4,04d812ada11a1cd2d4b556f53574513a8fb3cea6,2019-01-01 00:00:00,01/01/2019 12:00:00 AM,673.0,2.3,1,41.938666,-87.711211,41.924347,-87.734740,2.8,2.2,1.0,11,0.64607,0.69299

In [4]:
#data.drop(["Unnamed: 0","Trip ID", "Trips Pooled"], axis=1).to_csv("10_percent_consump.csv")