In [1]:
import pandas as pd
import numpy as np

giant_file_path = r"C:\Users\Adrian\Downloads\Transportation_Network_Providers_-_Trips_-_2019.csv"
test_file_path = r"C:\Users\Adrian\Downloads\Transportation_Network_Providers_-_Vehicles.csv"

In [2]:
def reduce_csv(chunk, columns, reduction_param):
    selected_df = chunk[columns]
    filters = np.random.random((len(selected_df.index), 1))
    return selected_df[(filters < reduction_param )]

In [3]:
filter_columns_cars = ["MONTH_REPORTED", "STATE", "MAKE", "MODEL"]
filter_columns_trips = ["Trip ID", "Trip Start Timestamp", "Trip End Timestamp", "Trip Seconds", "Trip Miles", "Trips Pooled", "Pickup Centroid Latitude", "Pickup Centroid Longitude", "Dropoff Centroid Latitude", "Dropoff Centroid Longitude"]


created_df = pd.DataFrame(columns = filter_columns_trips)

chunksize = 10 ** 6
for chunk in pd.read_csv(giant_file_path, chunksize=chunksize):
    temp_df = reduce_csv(chunk, filter_columns_trips, 0.1)
    created_df = pd.concat([created_df, temp_df])

created_df

,Trip ID,Trip Start Timestamp,Trip End Timestamp,Trip Seconds,Trip Miles,Trips Pooled,Pickup Centroid Latitude,Pickup Centroid Longitude,Dropoff Centroid Latitude,Dropoff Centroid Longitude
8,01b191b2dd282fa6cb39a9e2e152ca33262ae3dc,01/01/2019 12:00:00 AM,01/01/2019 12:30:00 AM,2223,25.9,1,41.929297,-87.798032,NaN,NaN
10,01fb7b0a39770bf4030110323f25e564bd46deb0,01/01/2019 12:00:00 AM,01/01/2019 12:00:00 AM,249,0.8,1,41.970245,-87.713435,41.964652,-87.721017
15,02de4893ce2de28b50976cc723f98cc8d325f9d5,01/01/2019 12:00:00 AM,01/01/2019 12:15:00 AM,445,1.7,1,41.85935,-87.617358,41.863423,-87.653757
29,04d812ada11a1cd2d4b556f53574513a8fb3cea6,01/01/2019 12:00:00 AM,01/01/2019 12:00:00 AM,673,2.3,1,41.938666,-87.711211,41.924347,-87.73474
34,050c7685dda55a3762c297406e18e2d9a4653eeb,01/01/2019 12:00:00 AM,01/01/2019 12:30:00 AM,1162,6.9,1,41.785999,-87.750934,41.747534,-87.67077
...,...,...,...,...,...,...,...,...,...,...
111850689,fbeca8d7bfb9856e38fd208e4f5d104b98c59538,12/31/2019 11:45:00 PM,01/01/2020 12:00:00 AM,818,4.3,1,41.921126,-87.699754,41.907492,-87.63576
111850704,fcd34ddb0e05b33d39cbf8ec1b6f320854c091a2,12/31/2019 11:45:00 PM,12/31/2019 11:45:00 PM,539,1.4,1,41.905858,-87.630865,41.893216,-87.637844
111850719,fe39e6ce75f2620066cd9334720509ce4f2da21f,12/31/2019 11:45:00 PM,01/01/2020 12:00:00 AM,258,0.9,1,42.009623,-87.670167,42.001571,-87.695013
111850723,fe8b0a37f027dea42acdc28b309d61006b71c544,12/31/2019 11:45:00 PM,01/01/2020 12:00:00 AM,989,5.7,1,NaN,NaN,41.67404,-87.651524
111850729,feef573a6fd83262d5f678dbe059f3da5d9bbeae,12/31/2019 11:45:00 PM,01/01/2020 12:00:00 AM,654,6.9,1,41.878594,-87.730232,NaN,NaN

In [4]:
#created_df.to_csv("10_percent_trips.csv")